#!/bin/bash

cd $(dirname $0)

# if egoadmin id is not 1000, update /etc/passwd (user's group must be root)
if [ "$(id -u)" != "1000" ]; then
    echo egoadmin id is $(id -u)
    sed "s|egoadmin:x:1000|egoadmin:x:$(id -u)|g" /etc/passwd > /tmp/passwd
    cat /tmp/passwd > /etc/passwd
    rm /tmp/passwd
fi

# resolve master IP
if [ -f "/shared/${SHARED_TOP_SUBDIR}/kernel/conf/hosts" ]; then
    cp /shared/${SHARED_TOP_SUBDIR}/kernel/conf/hosts /opt/ibm/spectrumcomputing/kernel/conf/hosts
fi

if [ -f "/opt/ibm/spectrumcomputing/scripts/configmap/hosts" ]; then
    cp /opt/ibm/spectrumcomputing/scripts/configmap/hosts /opt/ibm/spectrumcomputing/kernel/conf/hosts 
fi

# join the cluster
sed -i -e "s|^EGO_MASTER_LIST=.*|EGO_MASTER_LIST=master|g" /opt/ibm/spectrumcomputing/kernel/conf/ego.conf
. /opt/ibm/spectrumcomputing/profile.platform

if [ -z "${CLUSTER_USER}" ]; then
    CLUSTER_USER=Admin
fi

if [ -z "${CLUSTER_PASS}" ]; then
    CLUSTER_PASS=Admin
fi

if [ -f "/opt/ibm/spectrumcomputing/scripts/users/${CLUSTER_USER}" ]; then
    CLUSTER_PASS=$(base64 -d /opt/ibm/spectrumcomputing/scripts/users/${CLUSTER_USER}) 
fi

echo Deploy new app version

# waiting cluster is up
for I in 1 2 3 4 6 
do
    if egosh user logon -u Admin -x Admin; then
        break;
    fi
    echo "Waiting cluster to start up $I/6"
    sleep 10s
done

egosh consumer add /SampleAppCPP -g ComputeHosts,ManagementHosts -u Admin,Guest -e egoadmin

echo Deploy new package version
soamdeploy add SampleServiceCPP -p SampleServiceCPP.tgz -c /SampleAppCPP -f -u ${CLUSTER_USER} -x ${CLUSTER_PASS} 
soamreg SampleApp.xml -f -u ${CLUSTER_USER} -x ${CLUSTER_PASS}

echo Submit workload
while true; do
    ./AsyncClient
    sleep 1m

    # update master IP if changed
    if [ -f "/shared/${SHARED_TOP_SUBDIR}/kernel/conf/hosts" ]; then
        cp /shared/${SHARED_TOP_SUBDIR}/kernel/conf/hosts /opt/ibm/spectrumcomputing/kernel/conf/hosts
    fi

    if [ -f "/opt/ibm/spectrumcomputing/scripts/configmap/hosts" ]; then
        cp /opt/ibm/spectrumcomputing/scripts/configmap/hosts /opt/ibm/spectrumcomputing/kernel/conf/hosts 
    fi
done
